// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./components/Card/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FloatMenu: typeof import('./components/FloatMenu/index.vue')['default']
    Indev: typeof import('./components/FloatMenu/index.vue')['default']
    Monitor: typeof import('./components/Monitor/index.vue')['default']
    OInput: typeof import('./components/OInput/index.vue')['default']
    ProgressCard: typeof import('./components/ProgressCard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskCard: typeof import('./components/Monitor/TaskList/TaskCard/index.vue')['default']
    TaskList: typeof import('./components/Monitor/TaskList/index.vue')['default']
    TestTemplate: typeof import('./components/TestTemplate/index.vue')['default']
    Toolbar: typeof import('./components/Toolbar/index.vue')['default']
    VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
  }
}
